### ISSUE TITLE
app.use() requires a middleware function

### ISSUE THREAD

**Issue by Mazuco** [PacktPublishing/Web-Development-with-MongoDB-and-Node-Third-Edition#2]
There is a problem with this line:

app.use(multer({ dest: path.join(__dirname, 'public/upload/temp')}));

When run: 

> node server.js

/root/imgPloadr/node_modules/express/lib/application.js:210
    throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function

**Comment by ShavingSeagull** [comment]
> 
> 
> There is a problem with this line:
> 
> app.use(multer({ dest: path.join(__dirname, 'public/upload/temp')}));
> 
> When run:
> 
> > node server.js
> 
> /root/imgPloadr/node_modules/express/lib/application.js:210
> throw new TypeError('app.use() requires a middleware function')
> ^
> 
> TypeError: app.use() requires a middleware function

Use this instead:

`app.use(multer({
        dest: path.join(__dirname, 'public/upload/temp')
    }).single('file'));`

**Comment by Mazuco** [comment]
ok, thanks

**Comment by ShavingSeagull** [comment]
Actually, Mazuco, scratch that. You're likely going to run into a massive problem with the current version of Multer because they changed their API - I've just managed to resolve it, sort of. You're better off uninstalling Multer:

`npm uninstall multer`

and installing the older version used in the book, before the API change:

`npm install multer@0.1.8`

Then the code works as in the book; you won't need to apply the original change I mentioned in my first reply. One thing to note, though - you **must** put the line `routes(app);` in the configure.js file at the end, right before `return app;`, otherwise you're going to get the headache that I've had with this, wondering why Multer isn't creating the files object in the request.

I like the author's writing style, but I don't know what he was smoking when he wrote parts of this book.

**Comment by Mazuco** [comment]
ok, thanks
